name: Build and Package for macOS

on:
  push:
    branches:
      - Pre-released  # Trigger this workflow on push to the main branch

jobs:
  build:
    runs-on: macOS-latest  # Use the latest macOS runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout your repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.8  # Replace with your Python version

      - name: Install dependencies
        run: |
          pip install pyinstaller
          npm install -g create-dmg

      - name: Install Pillow
        run: pip install Pillow

      - name: Download FFmpeg
        run: |
          curl -L https://evermeet.cx/ffmpeg/ffmpeg-4.4.zip -o ffmpeg.zip
          unzip ffmpeg.zip
          mv ffmpeg ffmpeg-darwin-x86_64
          chmod +x ffmpeg-darwin-x86_64

      - name: Build Application with PyInstaller
        run: |
            pyinstaller --onefile --clean --windowed --hidden-import=engineio.async_drivers.eventlet --hidden-import=engineio.async_drivers.gevent_uwsgi --hidden-import=engineio.async_drivers.gevent --hidden-import=engineio.async_drivers --hidden-import=gevent --hidden-import=engineio.async_drivers.threading --hidden-import=pygame.freetype --hidden-import=encodings.utf_16_le --add-binary "ffmpeg-darwin-x86_64:." --add-data "icon.png:." --add-data "notification_sound.mp3:." --icon=icon.icns --distpath=. YoutubetoPremiere.py


      - name: Create DMG
        run: |
          create-dmg 'dist/YoutubetoPremiere' --dmg-title='YoutubetoPremiere' dist  # Adjust paths and titles as necessary

      - name: Get the release
        id: get_release
        uses: actions/github-script@v5
        with:
          script: |
            const { owner, repo } = context.repo
            const releases = await github.rest.repos.listReleases({ owner, repo })
            const preRelease = releases.data.find(release => release.prerelease && release.tag_name === 'V1.1')
            return preRelease.upload_url

      - name: Upload DMG to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.result }}
          asset_path: ./dist/YoutubetoPremiere.dmg
          asset_name: YoutubetoPremiere.dmg
          asset_content_type: application/x-diskcopy